### ISSUE TITLE
Статья 19.3 Изменение критерия отстраниения

### ISSUE THREAD

**Issue by anton-kochev** [football-it-league-dnipro/football-it-dp-ua#37]
Для приведения условий отстранения к общепринятому в городских соревнованиях виду, предлагаю внести изменения в определение пункта 3, статьи 19 действующего регламента.

#### Стаття 19. Облік дисциплінарних санкцій, що застосовуються арбітром
3. За кожні **три** жовті картки, отримані в матчах, футболіст підлягає відстороненню на один матч.

Мотивация:
- приведение к общепринятой практике;
- ужесточение в пользу более аккуратной игры со стороны участников;

**Comment by pastore** [comment]
Хорошая идея,
но я предлагаю сделать не **три** а **две** жёлтые карты.

Мотивация:

- нет статистики на руках, потому что на данный момент таблица по картам пустая, но за чемпионат осень 2019 я не заметил чтоб у кого то было 3 карты, могу ошибаться но в любом случае если и были то очень мало. Какой вывод из этого: слишком большая цифра чтоб набрать кому то 3 карты. 
А всё таки было бы интересно чтоб этот пункт срабатывал чаще, конечно не для того чтоб было больше нарушений а для увеличения зрелищности чемпионата.
Как я это вижу: ввиду того что предыдущий чемпионат показал, больше всего и последующие покажут, большую конкуренцию на всех фронтах турнирной таблицы, отсутствие в ключевых матчах игроков а особенно лидеров могут сказаться на общем результате.
Поэтому командам придётся считать и карты, чтоб не потерять очки на "ровном" месте.

**Comment by anton-kochev** [comment]
@pastore В первых сезонах было два условия при выполнении одного из которых игрок получал отстранение на одну игру: 
- желтая карточка в двух играх соревнований подряд (упразднено так как его посчитали слишком строгим);
- четыре желтых карточки (действует до сих пор);

В осенних соревнованиях 2019 максимальное количество карточек полученное одним из игроков - 3 (таких участников 5 на две лиги).

**Comment by steamhammer** [comment]
Предложение принято
https://github.com/football-it-league-dnipro/football-it-dp-ua/pull/42
