### ISSUE TITLE
Введение понятия игрока-старожила

### ISSUE THREAD

**Issue by OleksiiKipra** [football-it-league-dnipro/football-it-dp-ua#39]
Чтобы дать возможность игрокам, которые давно играют за одну и ту же команду, продолжать играть за данную команду даже если игрок сменил компанию, на которую работает, предлагаю ввести понятие футболист-старожил. Таким игроком будет считаться человек, который представлял одну и ту же команду минимум 4 сезона с возможными пропусками сезонов и не представлял за этот период любую другую команду IT-лиги Днепра до текущего момента. Такой игрок не будет относится к группе футболистов-легионеров, даже если он не работает на компанию, за команду которой он играет.

Мотивация:
Команды у нас не профессиональные, оплаты за участие в играх не получаем. По большей части играем для своего развития и удовольствия. Есть люди, которые играют командой длинный период времени. Но проекты в IT компаниях могут закрываться, так же люди могут найти себе более комфортные условия работы. При этом эти же люди хотят продолжать играть за команду, за которую играли годами, со своими друзьями. Реалии IT-рынка Днепра и ограничения на количество легионеров в команде не позволяют всем таким старожилам команды представлять команду в соревнованиях.
В профессиональном спорте есть понятие натурализации для избежания превышения количества легионеров. У нас же в "ламповом" чемпионате пока что нет возможности оставить в команде всех, кто когда-то по правилам соревнований представлял команду, т.к. еще несколько человек сменили работу.

возможный вариант изменения в регламент для ввода понятия футболист-старожил:
https://github.com/football-it-league-dnipro/football-it-dp-ua/pull/38

**Comment by anton-kochev** [comment]
Спасибо за предложение @OleksiiKipra 

Альтернативное предложение: игрок, который был включен в заявку команды на сезон 4 (четыре) раза подряд (не учитываются сезоны в которых команда не принимала участия в соревнованиях, при условии, что данный игрок не был заявлен за какую-либо другую команду) может быть заявлен за эту команду в качестве "футболиста-легионера", при этом он не учитывается при подсчете лимита на легионеров.
Таким образом данная льгота выполняется:
- для одной и только одной пары футболист-команда;
- для смягчения правил участия для игроков, которые продолжительное время представляют одну и ту же компанию;

**Comment by OleksiiKipra** [comment]
@anton-kochev В моей формулировке есть возможность заявить за команду человека, который по состоянию здоровья или из-за ограничения старых правил пропустил сезон или несколько (когда команда играла, но человек не был в заявке), но он ни за кого другого заявлен не был.
К примеру, было у команды 3 легионера и резко еще пару человек превратились в легионеров. Двоих не смогли заявить на сезон, хоть и хотели, и люди не играли ни за кого. Но команда играла и 2 человека, получается, были не в заявке. Моё предложение направлено на то, чтобы не пришлось отказываться от игроков, которые давно в команде, пусть они и сменили работу.

**Comment by anton-kochev** [comment]
В таком случае можно немного ослабить правило: «_...на сезон 4 (четыре) раза подряд (не учитывая сезон(ы), в котором данный игрок не был заявлен за какую-либо другую команду)..._»

**Comment by OleksiiKipra** [comment]
"какую-либо другую команду" тут слово "другую" лишнее, по-моему. мы хотим не считать сезон(ы), в которых человек вообще не играл. если он заявлен за нашу команда на сезон, то он не заявлен на этот сезон за другую команду и игровой сезон не попадет в подсчет из-за этого слова.

получается, в твоём варианте при правильной формулировке правила, можно будет больше легионеров заявить и таблица дополнительной оплаты за количество легионеров расширится?
в моем варианте за старожил не надо доплачивать. это не так принципиально, но надо понимать на что рассчитывать.

**Comment by EdgarGaytsuk** [comment]
Предлагаю добавить ограничения на таких людей, если правило будет внедрено

**Comment by SergeyBril** [comment]
> * для одной и только одной пары футболист-команда

@anton-kochev не понял эту строчку, тоесть может быть только один "старожил" в команде?

**Comment by SergeyBril** [comment]
на мой взгляд хорошо было бы сделать так:
3 легионера + 3 старожила (каждый из которых был заявлен в команду 4 сезона не в качестве легионера и не был заявлен за какую-либо другую команду за этот период)

**Comment by esputnik** [comment]
Это слишком много.
3 легионера и 1 старожила на 5 человек команды
т.е. если 5 в заявке то + 1 сторожила, 10 в заявке + 2, 15 + 3

**Comment by EdgarGaytsuk** [comment]
слишком много сторожил тогда.
Надо привязать к кол-ву игроков в заявке. 
1 сторожила на 5 человек в заявке.

**Comment by anton-kochev** [comment]
@SergeyBril Изначальная формулировка допускает ситуацию при которой один и тот же футболист может быть"сторожилой" по отношению к более чем одной компании. Моя формулировка исключает такую возможность

**Comment by anton-kochev** [comment]
@OleksiiKipra @SergeyBril @EdgarGaytsuk 
В качестве эксперимента можно ограничить количество сторожил в команде до **двух**

**Comment by OleksiiKipra** [comment]
@anton-kochev "... до текущего момента" эти слова в изначальной формулировке исключали возможность одного игрока быть старожилом в двух и более командах одновременно. только в самой последней команде, за которую он играл(ет).

**Comment by anton-kochev** [comment]
> @anton-kochev "... до текущего момента" эти слова в изначальной формулировке исключали возможность одного игрока быть старожилом в двух и более командах одновременно. только в самой последней команде, за которую он играл(ет).

Перечитал. Формулировка неоднозначная.

**Ситуация**: Иванов сыграл 4 сезона за **TechService** и 4 сезона за **SoftwareProduction**. Не важно в какой последовательности. Для какой команды он "сторожил"?

**Comment by OleksiiKipra** [comment]
"Таким игроком будет считаться человек, который представлял одну и ту же команду минимум 4 сезона с возможными пропусками сезонов и не представлял за этот период любую другую команду IT-лиги Днепра до текущего момента."

Тут как раз важна последовательность. Т.к. для определения попал ли человек под правило старожила, мы берем его активность от какого момента времени до текущего момента.
Если Иванов сыграл за TechService 4 сезона, а потом играл за SoftwareProduction, то он не старожила в TechService.

**Comment by ws45** [comment]
Как будем решать принимать ли какую-то поправку или нет?

**Comment by steamhammer** [comment]
@ws45 принимать окончательное решение будет оргкомитет. Основываясь на пожеланиях участников, востребованности поправки, возможности ее имплементации и т.д.

**Comment by antontykhonov** [comment]
Отличная идея, ребята!

**Comment by anton-kochev** [comment]
> Как будем решать принимать ли какую-то поправку или нет?

Четкой процедуры в данный момент нет. Она пока только «обкатывается». Но можно сказать, что мы точно будем смотреть на количество 👍🏼👎🏼 и общий ход осуждения (аргументация «за» и «против»)

**Comment by VitalyZhabchyk** [comment]
Идея хорошая с игроком «старожилом».
Думаю нет смысла ограничивать количество таких «старожилов» в команде.
В IT средний срок жизни сотрудника в компании 1.5-2 года.
Многие команды играют уже давно. И многие остаются лояльны той компании, где играли.
4 сезона это 2 года, но игроки меняют компании чаще, но хотят оставаться в команде и дальше.
Может ввести два понятия:
- старожил сотрудник (игрок который работал в компании, играл за неё, ушёл в другую компанию, но продолжает играть за свою старую компанию)
- старожил легионер (обычный легионер, который играет за одну компанию 3-4 сезона)

Старожил сотрудник не считается легионером когда он поменял компанию, но не менял команду, неважно сколько сезонов он отыграл за них.

Старожил легионер перестаёт считаться легионером через 3-4 сезона. Нужно для того, чтобы можно было привлекать новых легионеров, усиливать команду.

**Comment by steamhammer** [comment]
Предложение принято
https://github.com/football-it-league-dnipro/football-it-dp-ua/pull/42
