### ISSUE TITLE
Определение футбольных щитков как обязательного атрибута для участников

### ISSUE THREAD

**Issue by anton-kochev** [football-it-league-dnipro/football-it-dp-ua#40]
Внесение изменений в статью с требованиями к игровой форме участников соревнований

#### Стаття 9. Вимоги до ігрової форми (екіпірування) футболіста
1. Ігрова форма футболіста складається з футболки, шортів, гетрів, щитків та взуття

Мотивация: усиление мер безопасности направленное на уменьшение травматичности

**Comment by twichez** [comment]
это личное дело каждого, если захотеть кого то травмировать, то и щитки не спасут

**Comment by OleksiiKipra** [comment]
Раз уж заговорили о здоровье людей, то предлагаю разрешить носить на матчах шапки, шарфы, баффы. Игры иногда происходят при довольно низкой температуре. В последнем матче мне судья запретил играть в баффе на шее, в котором я играл в предыдущих сезонах без проблем, и вопрос возможного переохлаждения шею судью абсолютно не волновал.

**Comment by twichez** [comment]
кто такой? предлагаю отстранить судей которые играют в командах либо тренируют их!

**Comment by esputnik** [comment]
@twichez отстранить от чего?
Судить свою команду?
Судить твою команду?
Судить твою лигу?
Судить чужую  лигу?
Судить сам чемпионат?
Находиться на хронометре?

**Comment by esputnik** [comment]
@OleksiiKipra Носить шапку может только вратарь, остальное запрещено для всех в целях безопасности.

**Comment by OleksiiKipra** [comment]
@esputnik собственно, я вратарь и мне запретили бафф на шею. думаю, если бы меня хотели задушить, отсутствие баффа меня бы не спасло.

**Comment by EdgarGaytsuk** [comment]
тебя могут дернуть за баф. надевай гольф с шеей

**Comment by OleksiiKipra** [comment]
а за шею гольфа дернуть не могут?

**Comment by EdgarGaytsuk** [comment]
могут, но это будет менее опасно, чем удушье от баффа.
Я думаю что общие правила футбола менять не стоит. 
Они писанные не нами.

**Comment by twichez** [comment]
> @twichez отстранить от чего?
> Судить свою команду?
> Судить твою команду?
> Судить твою лигу?
> Судить чужую лигу?
> Судить сам чемпионат?
> Находиться на хронометре?

Всё выше перечисленное.

**Comment by EdgarGaytsuk** [comment]
@twichez какие будут аргументы ко всему вышеперечисленному? Я лишь вижу только один аргумент к "Судить твою лигу?" - это потенциальное подсуживание. И согласен, что судья не может играть/тренировать и судить свою лигу

**Comment by steamhammer** [comment]
В этом тикете/ишью обсуждаем щитки и прочую экипу. Если у кого-то есть аргументированные предложения по другим темам - создавайте отдельный тикет. Спасибо.

**Comment by OleksiiKipra** [comment]
я бы оставил хотя бы вратарям право выбирать, надевать ли щитки.
мой стандартный эквип: перчатки, защита паха, наколенники, налокотники.
щитки я не надеваю, т.к. с ними гетры больше пережимают ноги и они быстрее устают. под щитки придется искать более свободные гетры, а это проблема.

**Comment by twichez** [comment]
ну давайте еще защиту паха сделаем обязательной

**Comment by pastore** [comment]
Крайне не советую вводить этот пункт.
Мотив: не думаю что отсутствие щитков за все года до этого причинило какого то ощутимого вреда футболистам и вряд ли это произойдёт после.
А вот игра с щиткам точно приносит постоянно дискомфорт.

**Comment by steamhammer** [comment]
Предложение отклонено.
